"""
render.py - Turn a Bomb into a self-contained source directory.

    OUT/
      bomb.c                 student copy of main (CMU or drill)
      phases.c               #includes the chosen phase templates in order
      bombdata.h             per-seed macros, nothing else
      support.[ch] phases.h driverlib.[ch]   shared runtime
      cmu/..., drills/...    the phase templates used
      Makefile.bomb          the one set of compiler flags
      answers.txt            one answer per phase
      answers_secret.txt     with the secret token and the secret answer
      SOLUTION.md            operator write-up: answers, walkthroughs, hints
      notes/stageN.md        student write-up, released after defusal
      hints/stageN-K.md      student hints, released over time
      manifest.json          kind, seed, variants, expected canaries

Only bomb and bomb.c ever reach a student. Output is a pure function of the
Bomb, so the same (kind, seed) always renders the same bytes.
"""

import hashlib
import json
import os
import shutil
import time

from .core import Raw

CSRC =os.path.join(os.path.dirname(os.path.abspath(__file__)), "csrc")
COMMON = ["support.c", "support.h", "phases.h", "driverlib.c", "driverlib.h"]
TOOLCHAIN = "gcc (Ubuntu 4.8.1-2ubuntu1~12.04) 4.8.1"


class RenderError(Exception):
    pass


# --------------------------------------------------------------------------
# C literals
# --------------------------------------------------------------------------

def _escape(ch, quote):
    """One character inside a C literal delimited by `quote`."""
    if ch == quote or ch == "\\":
        return "\\" + ch
    if 0x20 <= ord(ch) < 0x7F:
        return ch
    return "\\%03o" % (ord(ch) & 0xFF)


def c_string(s):
    return '"' + "".join(_escape(ch, '"') for ch in s) + '"'


def c_char(ch):
    return "'" + _escape(ch, "'") + "'"


def c_value(v):
    if isinstance(v, Raw):
        return v.text
    if isinstance(v, bool):
        return "1" if v else "0"
    if isinstance(v, int):
        return str(v)
    if isinstance(v, str):
        return c_string(v)
    if isinstance(v, (list, tuple)):
        items = []
        for x in v:
            if isinstance(x, str) and len(x) == 1:
                items.append(c_char(x))
            else:
                items.append(c_value(x))
        return "{" + ", ".join(items) + "}"
    raise RenderError("cannot render %r as C" % (v,))


# --------------------------------------------------------------------------
# generated sources
# --------------------------------------------------------------------------

def bombdata_h(bomb):
    out = ["/* bombdata.h - generated by bank/render.py for %s seed %d.",
           " * Do not edit. Do not distribute: these are the answers. */",
           "#ifndef BOMBDATA_H", "#define BOMBDATA_H", "",
           "#define NUM_PHASES  %d" % bomb.num_phases,
           "#define HAS_SECRET  %d" % (1 if bomb.has_secret else 0)]
    out[0] %= (bomb.kind, bomb.seed)
    if bomb.has_secret:
        out.append("#define SECRET_LINE %d" % bomb.secret_line)
        out.append("#define SECRET_WORD %s" % c_string(bomb.secret_word))
    for i, p in enumerate(bomb.phases):
        label = "secret phase" if p.slot == "secret" else "phase %d" % (i + 1)
        out += ["", "/* %s: %s (%s) */" % (label, p.slot, p.variant)]
        for name, value in p.macros:
            out.append("#define %s %s" % (name, c_value(value)))
    out += ["", "#endif", ""]
    return "\n".join(out)


def phases_c(bomb):
    out = ["/* phases.c - generated by bank/render.py. Every phase lives in this",
           " * one translation unit, as in the original bomb, so symbol order,",
           " * static-local names and data layout come out the same. */",
           "#include <stdio.h>", "#include <stdlib.h>",
           '#include "bombdata.h"', '#include "support.h"', '#include "phases.h"',
           ""]
    out += ['#include "%s"' % p.template for p in bomb.phases]
    return "\n".join(out) + "\n"


def _safe_title(s):
    for bad in ('"', "\\", "%", "*/", "\n"):
        if bad in s:
            raise RenderError("drill title may not contain %r" % bad)
    return s


def main_c(bomb):
    with open(os.path.join(CSRC, "common", bomb.main)) as f:
        src = f.read()
    if bomb.main == "drill_main.c":
        src = src.replace("@DRILL_ID@", _safe_title(bomb.drill_id))
        src = src.replace("@DRILL_TITLE@", _safe_title(bomb.drill_title))
    return src


# --------------------------------------------------------------------------
# write-ups
# --------------------------------------------------------------------------

def _label(bomb, i):
    p = bomb.phases[i]
    return "Secret phase" if p.slot == "secret" else "Phase %d" % (i + 1)


def solution_md(bomb):
    v = bomb.variants()
    out = ["# SOLUTION — %s, seed %d" % (bomb.kind, bomb.seed), "",
           "**운영자 전용. 학생에게 배포 금지.**", "",
           "- 종류: %s%s" % (bomb.title,
                           " (%s: %s)" % (bomb.drill_id, bomb.drill_title)
                           if bomb.drill_id else ""),
           "- 변형 계열: " + ", ".join("%s=%s" % (k, v[k]) for k in v),
           "", "## 정답 한 벌", "", "```"]
    out += bomb.answer_lines(with_secret=bomb.has_secret)
    out += ["```", ""]
    if bomb.has_secret:
        out += ["숨은 단계 진입: %d번째 줄 끝에 `%s`를 덧붙인다." %
                (bomb.secret_line + 1, bomb.secret_word), ""]
    for i, p in enumerate(bomb.phases):
        out += ["---", "", "## %s — %s (`%s`)" % (_label(bomb, i), p.title,
                                                 p.variant), "",
                "**정답**: " + p.answers, "", p.walkthrough.rstrip(), "",
                "**힌트**", ""]
        out += ["%d. %s" % (k + 1, h) for k, h in enumerate(p.hints)]
        out.append("")
    return "\n".join(out)


NOTE_CAVEAT = ("> 해설의 어셈블리는 대표적인 모양이다. 실제 주소·레지스터·명령어 "
               "순서는 폭탄마다 조금씩 다를 수 있으니 `objdump -d`로 직접 확인하라.")


def note_md(bomb, i):
    p = bomb.phases[i]
    return "# %s — %s\n\n%s\n\n%s\n\n**이 폭탄의 정답**: %s\n" % (
        _label(bomb, i), p.title, NOTE_CAVEAT, p.walkthrough.rstrip(),
        p.answers)


def hint_md(bomb, i, k):
    p = bomb.phases[i]
    return "# %s 힌트 %d/3\n\n%s\n" % (_label(bomb, i), k + 1, p.hints[k])


def manifest(bomb):
    return {
        "kind": bomb.kind,
        "seed": bomb.seed,
        "title": bomb.title,
        "drill_id": bomb.drill_id,
        "drill_title": bomb.drill_title,
        "num_phases": bomb.num_phases,
        "has_secret": bomb.has_secret,
        "variants": bomb.variants(),
        "canary": bomb.canary_set(),
        "toolchain": TOOLCHAIN,
        "phases": [{"number": i + 1, "slot": p.slot, "variant": p.variant,
                    "title": p.title} for i, p in enumerate(bomb.phases)],
    }


# --------------------------------------------------------------------------

def rmtree(path):
    """
    shutil.rmtree that rides out transient EACCES. On a Windows drive under
    WSL (/mnt/c) a virus scanner or the indexer can hold a file we just wrote
    for a moment.
    """
    for attempt in range(20):
        try:
            shutil.rmtree(path)
            return
        except FileNotFoundError:
            return
        except PermissionError:
            if attempt == 19:
                raise
            time.sleep(0.25)


def _prepare(out):
    if os.path.exists(out):
        if os.listdir(out) and not os.path.isfile(
                os.path.join(out, "manifest.json")):
            raise RenderError("%s exists and is not a rendered bomb; "
                              "refusing to overwrite" % out)
        rmtree(out)
    os.makedirs(out)


def _write(path, text):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)


def digest(out, skip=("bomb", ".fuzz_in")):
    """{relative path: sha256} of every rendered file (not build outputs)."""
    sums = {}
    for dirpath, _, files in os.walk(out):
        for name in files:
            if name in skip or name.endswith(".o"):
                continue
            path = os.path.join(dirpath, name)
            with open(path, "rb") as f:
                sums[os.path.relpath(path, out)] = \
                    hashlib.sha256(f.read()).hexdigest()
    return sums


def write(bomb, out):
    """Render bomb into directory out (replacing an earlier render)."""
    _prepare(out)
    for name in COMMON:
        shutil.copyfile(os.path.join(CSRC, "common", name),
                        os.path.join(out, name))
    shutil.copyfile(os.path.join(CSRC, "Makefile.bomb"),
                    os.path.join(out, "Makefile.bomb"))
    for p in bomb.phases:
        dst = os.path.join(out, p.template)
        os.makedirs(os.path.dirname(dst), exist_ok=True)
        shutil.copyfile(os.path.join(CSRC, p.template), dst)

    _write(os.path.join(out, "bomb.c"), main_c(bomb))
    _write(os.path.join(out, "phases.c"), phases_c(bomb))
    _write(os.path.join(out, "bombdata.h"), bombdata_h(bomb))
    _write(os.path.join(out, "answers.txt"),
           "\n".join(bomb.answer_lines()) + "\n")
    if bomb.has_secret:
        _write(os.path.join(out, "answers_secret.txt"),
               "\n".join(bomb.answer_lines(with_secret=True)) + "\n")
    _write(os.path.join(out, "SOLUTION.md"), solution_md(bomb))
    for i in range(len(bomb.phases)):
        _write(os.path.join(out, "notes", "stage%d.md" % (i + 1)),
               note_md(bomb, i))
        for k in range(3):
            _write(os.path.join(out, "hints", "stage%d-%d.md" % (i + 1, k + 1)),
                   hint_md(bomb, i, k))
    _write(os.path.join(out, "manifest.json"),
           json.dumps(manifest(bomb), indent=2, ensure_ascii=False) + "\n")
